# Generated by Django 4.0.3 on 2022-04-17 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('descriptions', models.TextField()),
                ('poster', models.ImageField(upload_to='{{Titles.name}}/arts/')),
                ('genre', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=120)),
                ('publisher', models.CharField(max_length=120)),
                ('translator', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('chapters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.chapters')),
            ],
        ),
        migrations.AddField(
            model_name='chapters',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.images'),
        ),
    ]
